# Alias personales
alias cdph="cd /mnt/Documents/Php"
alias cdpy="cd /mnt/Documents/Python"
alias cdja="cd /mnt/Documents/Java"
alias cdpr="cd /mnt/Documents/Pruebas"
alias cdjs="cd /mnt/Documents/Javascript"
alias cdsc="cd /mnt/Documents/Scripts"
alias cddo="cd /mnt/Downloads"
alias cdnv="cd /home/luis/.config/nvim"
alias venv="python3 -m virtualenv venv"
alias activate="test -d venv && source ./venv/bin/activate"
