# Alias personales
alias cdph="cd /mnt/Documents/Php"
alias cdpy="cd /mnt/Documents/Python"
alias cdja="cd /mnt/Documents/Java"
alias cdpr="cd /mnt/Documents/Pruebas"
alias cdjs="cd /mnt/Documents/Javascript"
alias cdjs="cd /mnt/Documents/Typescript"
alias cdsc="cd /mnt/Documents/Scripts"
alias cddo="cd /mnt/Downloads"
alias cdnv="cd /home/luis/.config/nvim"
# alias venv="python3 -m virtualenv venv"
# alias activate="test -d venv && source ./venv/bin/activate"
alias kssh="kitty +kitten ssh"
alias cat="bat --paging=never"
alias dc="docker compose"
alias dcf="docker compose up -d --build --force-recreate"
alias dcu="docker compose up -d"
alias dcl="docker compose logs -f"
alias dcd="docker compose down"
alias dcp="docker compose ps"
